library(data.table)
library(bit64)

r1 = fread("~/Documents/Recommender\ system\ study/1.csv")
r2 = fread("~/Documents/Recommender\ system\ study/2.csv")
r3 = fread("~/Documents/Recommender\ system\ study/3.csv")
r4 = fread("~/Documents/Recommender\ system\ study/4.csv")
r5 = fread("~/Documents/Recommender\ system\ study/5.csv")
r6 = fread("~/Documents/Recommender\ system\ study/6.csv")
r7 = fread("~/Documents/Recommender\ system\ study/7.csv")
r8 = fread("~/Documents/Recommender\ system\ study/8.csv")
r9 = fread("~/Documents/Recommender\ system\ study/9.csv")
r10 = fread("~/Documents/Recommender\ system\ study/10.csv")
r11= fread("~/Documents/Recommender\ system\ study/11.csv")
r12 = fread("~/Documents/Recommender\ system\ study/12.csv")
r13 = fread("~/Documents/Recommender\ system\ study/13.csv")
r14 = fread("~/Documents/Recommender\ system\ study/14.csv")
r15 = fread("~/Documents/Recommender\ system\ study/15.csv")
r16 = fread("~/Documents/Recommender\ system\ study/16.csv")
r17 = fread("~/Documents/Recommender\ system\ study/17.csv")
r18 = fread("~/Documents/Recommender\ system\ study/18.csv")
r19 = fread("~/Documents/Recommender\ system\ study/19.csv")
r20 = fread("~/Documents/Recommender\ system\ study/20.csv")
r21 = fread("~/Documents/Recommender\ system\ study/21.csv")
r22 = fread("~/Documents/Recommender\ system\ study/22.csv")
r23 = fread("~/Documents/Recommender\ system\ study/23.csv")
r24 = fread("~/Documents/Recommender\ system\ study/24.csv")
r25 = fread("~/Documents/Recommender\ system\ study/25.csv")
r26 = fread("~/Documents/Recommender\ system\ study/26.csv")
r27 = fread("~/Documents/Recommender\ system\ study/27.csv")
r28 = fread("~/Documents/Recommender\ system\ study/28.csv")
r29 = fread("~/Documents/Recommender\ system\ study/29.csv")
r30 = fread("~/Documents/Recommender\ system\ study/30.csv")
r31 = fread("~/Documents/Recommender\ system\ study/31.csv")
r32 = fread("~/Documents/Recommender\ system\ study/32.csv")
r33 = fread("~/Documents/Recommender\ system\ study/33.csv")
r34 = fread("~/Documents/Recommender\ system\ study/34.csv")
r35 = fread("~/Documents/Recommender\ system\ study/35.csv")
r36 = fread("~/Documents/Recommender\ system\ study/36.csv")
r37 = fread("~/Documents/Recommender\ system\ study/37.csv")
r38 = fread("~/Documents/Recommender\ system\ study/38.csv")
r39 = fread("~/Documents/Recommender\ system\ study/39.csv")
r40 = fread("~/Documents/Recommender\ system\ study/40.csv")

device = rbind(r1,r2,r3,r4,r5,r6,r7,r8,r9,r10,r11,r12,r13,r14,r15,r16,r17,r18,r19,r20,r21,r22,r23,r24,r25,r26,r27,r28,r29,r30,r31,r32,r33,r34,r35,r36,r37,r38,r39,r40)

rm(r1) 
rm(r2)
rm(r3) 
rm(r4) 
rm(r5)
rm(r6) 
rm(r7)
rm(r8) 
rm(r9) 
rm(r10)
rm(r11) 
rm(r12)
rm(r13) 
rm(r14) 
rm(r15)
rm(r16) 
rm(r17)
rm(r18) 
rm(r19) 
rm(r20)
rm(r21) 
rm(r22)
rm(r23) 
rm(r24) 
rm(r25)
rm(r26) 
rm(r27)
rm(r28) 
rm(r29) 
rm(r30)
rm(r31) 
rm(r32)
rm(r33) 
rm(r34) 
rm(r35)
rm(r36) 
rm(r37)
rm(r38) 
rm(r39) 
rm(r40)
colnames(device) = c("adid", "uid", "deviceid", "device created", "device model", "device comment", "deviceinfo","marketing name", "deviceinfo", "platformid", "platfortype", "screenwidth", "screensize", "swipecount", "clickcount", "closecount", "totalviewtime", "relativeviewtime", "adrelevance", "adrecall", "validrequests", "deliveredimp", "monetizedimp")

dev_rel = aggregate(device$adrelevance, by = list(device$`device model`), FUN=mean )
dev_recall = aggregate(device$adrecall, by = list(device$`device model`), FUN=mean )
dev_totaltime = aggregate(device$totalviewtime, by = list(device$`device model`), FUN=mean )
dev_relativetime = aggregate(device$relativeviewtime, by = list(device$`device model`), FUN=mean )

colnames(dev_rel)[1] = "Device Id"
colnames(dev_rel)[2] = "Mean adrelevance"
colnames(dev_recall)[1] = "Device Id"
colnames(dev_recall)[2] = "Mean adrecall"
colnames(dev_totaltime)[1] = "Device Id"
colnames(dev_totaltime)[2] = "Mean totaltime"
colnames(dev_relativetime)[1] = "Device Id"
colnames(dev_relativetime)[2] = "Mean relativetime"

temp_1 = merge(dev_rel, dev_recall, by = "Device Id")
temp_2 = merge(temp_1, dev_totaltime, by = "Device Id")
device_metrics = merge(temp_2, dev_relativetime, by = "Device Id")
rm(temp_1)
rm(temp_2)

